/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DimCrew {
  id: Generated<number>;
  mongo_id: string;
  name: string;
  synced_at: Generated<Timestamp>;
  type: string;
}

export interface DimDailyReport {
  approved: Generated<boolean>;
  archived: Generated<boolean>;
  crew_id: number;
  id: Generated<number>;
  jobsite_id: number;
  mongo_id: string;
  payroll_complete: Generated<boolean>;
  report_date: Timestamp;
  synced_at: Generated<Timestamp>;
}

export interface DimEmployee {
  archived_at: Timestamp | null;
  id: Generated<number>;
  job_title: string | null;
  mongo_id: string;
  name: string;
  synced_at: Generated<Timestamp>;
}

export interface DimEmployeeRate {
  effective_date: Timestamp;
  employee_id: number;
  id: Generated<number>;
  rate: Numeric;
  synced_at: Generated<Timestamp>;
}

export interface DimJobsite {
  active: Generated<boolean>;
  archived_at: Timestamp | null;
  id: Generated<number>;
  jobcode: string | null;
  mongo_id: string;
  name: string;
  synced_at: Generated<Timestamp>;
}

export interface FactEmployeeWork {
  archived_at: Timestamp | null;
  crew_id: number;
  daily_report_id: number;
  day_of_week: number;
  employee_id: number;
  end_time: Timestamp;
  hourly_rate: Numeric;
  hours: Generated<Numeric | null>;
  id: Generated<number>;
  job_title: string;
  jobsite_id: number;
  mongo_id: string;
  month: number;
  start_time: Timestamp;
  synced_at: Generated<Timestamp>;
  total_cost: Generated<Numeric | null>;
  week: number;
  work_date: Timestamp;
  year: number;
}

export interface SchemaMigrations {
  version: string;
}

export interface DB {
  dim_crew: DimCrew;
  dim_daily_report: DimDailyReport;
  dim_employee: DimEmployee;
  dim_employee_rate: DimEmployeeRate;
  dim_jobsite: DimJobsite;
  fact_employee_work: FactEmployeeWork;
  schema_migrations: SchemaMigrations;
}
