apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-concrete-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web-concrete
  template:
    metadata:
      labels:
        component: web-concrete
    spec:
      containers:
        - name: client
          image: itsdevin/bow-mark-concrete-client:$COMMIT_SHA1
          resources:
            requests:
              cpu: "2000m"
              memory: "4000Mi"
            limits:
              cpu: "2500m"
              memory: "5000Mi"
          ports:
            - containerPort: 3001
