apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-concrete-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web-concrete
  template:
    metadata:
      labels:
        component: web-concrete
    spec:
      containers:
        - name: client
          image: itsdevin/bow-mark-concrete-client:$COMMIT_SHA1
          resources:
            requests:
              cpu: "800m"
              memory: "1600Mi"
            limits:
              cpu: "950m"
              memory: "1900Mi"
          ports:
            - containerPort: 3001
