apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-concrete-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web-concrete
  template:
    metadata:
      labels:
        component: web-concrete
    spec:
      containers:
        - name: client
          image: itsdevin/bow-mark-client:$COMMIT_SHA1
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: "/app/.env.local"
              subPath: ".env.local"
              name: env-file
              readOnly: true
      volumes:
        - name: env-file
          configMap:
            defaultMode: 420
            items:
              - key: .env
                path: .env.local
            name: client-concrete-env
