apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-worker-restart
spec:
  schedule: "0 7 * * *" # This is for UTC-7, adjust for daylight savings as necessary
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: worker-restart
            image: bitnami/kubectl
            command: ["/bin/sh", "-c"]
            args:
              - "kubectl rollout restart deployment worker-deployment && kubectl rollout restart deployment worker-concrete-deployment"
          restartPolicy: OnFailure
