apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-concrete-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: server-concrete
  template:
    metadata:
      labels:
        component: server-concrete
    spec:
      containers:
        - name: server
          image: itsdevin/bow-mark-server:$COMMIT_SHA1
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "250m"
              memory: "5000Mi"
            limits:
              cpu: "1000m"
              memory: "2000Mi"
          env:
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: Concrete
            - name: APP_TYPE
              value: api
            - name: SEARCH_GROUP
              value: bow-mark-concrete
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: concrete
                  key: mongoURI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: general
                  key: jwtSecret
            - name: SPACES_NAME
              valueFrom:
                secretKeyRef:
                  name: spaces
                  key: name
            - name: SPACES_REGION
              valueFrom:
                secretKeyRef:
                  name: spaces
                  key: region
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces
                  key: key
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: spaces
                  key: secret
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: email
                  key: email
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email
                  key: username
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email
                  key: password
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: email
                  key: host
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: email
                  key: port
            - name: SEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: search
                  key: host
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: search
                  key: apiKey
