apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: itsdevin/bow-mark-server:$COMMIT_SHA1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: mongoURI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: jwtSecret
            # - name: SPACES_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: server-secrets
            #       key: spacesName
            # - name: SPACES_REGION
            #   valueFrom:
            #     secretKeyRef:
            #       name: server-secrets
            #       key: spacesRegion
            # - name: SPACES_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: server-secrets
            #       key: spacesKey
            # - name: SPACES_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: server-secrets
            #       key: spacesSecret
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: elasticsearchPassword
