/**
 * Layer 3: Report query tests
 *
 * These tests operate entirely within PostgreSQL — no MongoDB involved.
 * They:
 *   1. Insert raw rows directly into PostgreSQL using Kysely
 *   2. Call the report query method via the resolver instance
 *   3. Assert the aggregated result
 *
 * The resolver's getDayReports / getEmployeesForDay queries filter on
 * dim_daily_report.approved = true, so seed data must set approved: true.
 * The fact_employee_work.hours and total_cost columns are generated by
 * PostgreSQL from start_time / end_time / hourly_rate — never inserted directly.
 */

import { truncateAllPgTables, seedPgReportData } from "@testing/vitestPgDB";
import { db } from "../../db";
import JobsiteReportPGResolver from "../../graphql/resolvers/jobsiteReportPG";

const resolver = new JobsiteReportPGResolver();

const SEED_START = new Date("2022-01-01T00:00:00.000Z");
const SEED_END = new Date("2022-12-31T23:59:59.999Z");

beforeEach(async () => {
  await truncateAllPgTables();
});

describe("jobsiteReport — employee work aggregation", () => {
  it("returns total employee hours = 14 for the seeded data", async () => {
    const { jobsiteMongoId } = await seedPgReportData();

    const report = await resolver.jobsiteReport(
      jobsiteMongoId,
      SEED_START,
      SEED_END
    );

    expect(report).not.toBeNull();
    // Sum of (8h + 6h) across both fact rows
    const totalHours = report!.dayReports.reduce(
      (sum, dr) => sum + dr.summary.employeeHours,
      0
    );
    expect(totalHours).toBe(14);
  });

  it("returns correct labour cost: (8 × 25) + (6 × 30) = $380", async () => {
    const { jobsiteMongoId } = await seedPgReportData();

    const report = await resolver.jobsiteReport(
      jobsiteMongoId,
      SEED_START,
      SEED_END
    );

    expect(report).not.toBeNull();
    const totalCost = report!.dayReports.reduce(
      (sum, dr) => sum + dr.summary.employeeCost,
      0
    );
    expect(totalCost).toBeCloseTo(380, 2);
  });
});

describe("jobsiteReport — data isolation", () => {
  it("does not include fact rows from a different jobsite", async () => {
    // Seed the primary jobsite (14 hours, $380)
    const { jobsiteMongoId, crewId } = await seedPgReportData();

    // Insert a second independent jobsite with its own daily report and work
    const otherJobsite = await db
      .insertInto("dim_jobsite")
      .values({
        mongo_id: "aaa000000000000000000001",
        name: "Other Jobsite",
        jobcode: "OTHER-001",
        active: true,
      })
      .returning("id")
      .executeTakeFirstOrThrow();

    const otherEmployee = await db
      .insertInto("dim_employee")
      .values({
        mongo_id: "aaa000000000000000000002",
        name: "Other Employee",
        job_title: "Operator",
      })
      .returning("id")
      .executeTakeFirstOrThrow();

    // dim_daily_report requires a crew_id — reuse the crew inserted by seedPgReportData
    const otherDr = await db
      .insertInto("dim_daily_report")
      .values({
        mongo_id: "aaa000000000000000000004",
        jobsite_id: otherJobsite.id,
        crew_id: crewId,
        report_date: new Date("2022-02-23"),
        approved: true,
      })
      .returning("id")
      .executeTakeFirstOrThrow();

    // 10 hours @ $50/hr for the OTHER jobsite — must not pollute jobsite 1
    await db
      .insertInto("fact_employee_work")
      .values({
        mongo_id: "aaa000000000000000000010",
        daily_report_id: otherDr.id,
        jobsite_id: otherJobsite.id,
        employee_id: otherEmployee.id,
        crew_id: crewId,
        crew_type: "Base",
        work_date: new Date("2022-02-23"),
        start_time: new Date("2022-02-23T06:00:00.000Z"),
        end_time: new Date("2022-02-23T16:00:00.000Z"),
        job_title: "Operator",
        hourly_rate: "50.00",
      })
      .execute();

    // Query jobsite 1 — result must be unchanged at $380
    const report = await resolver.jobsiteReport(
      jobsiteMongoId,
      SEED_START,
      SEED_END
    );

    expect(report).not.toBeNull();
    const totalCost = report!.dayReports.reduce(
      (sum, dr) => sum + dr.summary.employeeCost,
      0
    );
    expect(totalCost).toBeCloseTo(380, 2);

    const totalHours = report!.dayReports.reduce(
      (sum, dr) => sum + dr.summary.employeeHours,
      0
    );
    expect(totalHours).toBe(14);
  });
});

describe("jobsiteReport — approved filter", () => {
  it("excludes fact rows from unapproved daily reports", async () => {
    // Insert jobsite, employee, crew
    const jobsiteRow = await db
      .insertInto("dim_jobsite")
      .values({
        mongo_id: "bbb000000000000000000001",
        name: "Unapproved Jobsite",
        jobcode: "UNAPP-001",
        active: true,
      })
      .returning("id")
      .executeTakeFirstOrThrow();

    const employeeRow = await db
      .insertInto("dim_employee")
      .values({
        mongo_id: "bbb000000000000000000002",
        name: "Unapproved Employee",
        job_title: "Laborer",
      })
      .returning("id")
      .executeTakeFirstOrThrow();

    const crewRow = await db
      .insertInto("dim_crew")
      .values({
        mongo_id: "bbb000000000000000000003",
        name: "Unapproved Crew",
        type: "Base",
      })
      .returning("id")
      .executeTakeFirstOrThrow();

    // Daily report is NOT approved (default is false)
    const drRow = await db
      .insertInto("dim_daily_report")
      .values({
        mongo_id: "bbb000000000000000000004",
        jobsite_id: jobsiteRow.id,
        crew_id: crewRow.id,
        report_date: new Date("2022-02-23"),
        approved: false,
      })
      .returning("id")
      .executeTakeFirstOrThrow();

    // 8 hours of work — should be invisible because daily report is unapproved
    await db
      .insertInto("fact_employee_work")
      .values({
        mongo_id: "bbb000000000000000000010",
        daily_report_id: drRow.id,
        jobsite_id: jobsiteRow.id,
        employee_id: employeeRow.id,
        crew_id: crewRow.id,
        crew_type: "Base",
        work_date: new Date("2022-02-23"),
        start_time: new Date("2022-02-23T07:00:00.000Z"),
        end_time: new Date("2022-02-23T15:00:00.000Z"),
        job_title: "Laborer",
        hourly_rate: "25.00",
      })
      .execute();

    const report = await resolver.jobsiteReport(
      "bbb000000000000000000001",
      SEED_START,
      SEED_END
    );

    // No approved daily reports → no day reports → null or empty dayReports
    expect(report).not.toBeNull();
    expect(report!.dayReports).toHaveLength(0);
  });
});
