import { db } from "../db";

/**
 * Seeds a minimal set of dimension and fact rows for report query tests (Layer 3).
 *
 * Inserts two fact_employee_work rows for a single jobsite / daily report:
 *   - Employee A: 7am–3pm = 8 hours @ $25/hr  → $200 labour
 *   - Employee B: 8am–2pm = 6 hours @ $30/hr  → $180 labour
 *   Total: 14 hours, $380 labour cost
 *
 * The dim_daily_report is set to approved=true so it passes the resolver's
 * approval filter. The `hours` and `total_cost` columns in fact_employee_work
 * are generated by PostgreSQL and must NOT be inserted manually.
 *
 * Returns the internal PG ids for use in further assertions or additional inserts.
 */
export async function seedPgReportData(): Promise<{
  jobsiteId: string;
  jobsiteMongoId: string;
  crewId: string;
  employeeId: string;
  drId: string;
}> {
  const jobsiteRow = await db
    .insertInto("dim_jobsite")
    .values({
      mongo_id: "000000000000000000000001",
      name: "Test Jobsite",
      jobcode: "TEST-001",
      active: true,
    })
    .returning("id")
    .executeTakeFirstOrThrow();

  const employeeRow = await db
    .insertInto("dim_employee")
    .values({
      mongo_id: "000000000000000000000002",
      name: "Test Employee",
      job_title: "Laborer",
    })
    .returning("id")
    .executeTakeFirstOrThrow();

  const crewRow = await db
    .insertInto("dim_crew")
    .values({
      mongo_id: "000000000000000000000003",
      name: "Test Crew",
      type: "Base",
    })
    .returning("id")
    .executeTakeFirstOrThrow();

  const drRow = await db
    .insertInto("dim_daily_report")
    .values({
      mongo_id: "000000000000000000000004",
      jobsite_id: jobsiteRow.id,
      crew_id: crewRow.id,
      report_date: new Date("2022-02-23"),
      approved: true,
    })
    .returning("id")
    .executeTakeFirstOrThrow();

  // Employee A: 7am–3pm = 8 hours @ $25/hr = $200 labour
  await db
    .insertInto("fact_employee_work")
    .values({
      mongo_id: "000000000000000000000010",
      daily_report_id: drRow.id,
      jobsite_id: jobsiteRow.id,
      employee_id: employeeRow.id,
      crew_id: crewRow.id,
      crew_type: "Base",
      work_date: new Date("2022-02-23"),
      start_time: new Date("2022-02-23T07:00:00.000Z"),
      end_time: new Date("2022-02-23T15:00:00.000Z"),
      job_title: "Laborer",
      hourly_rate: "25.00",
    })
    .execute();

  // Employee B: 8am–2pm = 6 hours @ $30/hr = $180 labour
  await db
    .insertInto("fact_employee_work")
    .values({
      mongo_id: "000000000000000000000011",
      daily_report_id: drRow.id,
      jobsite_id: jobsiteRow.id,
      employee_id: employeeRow.id,
      crew_id: crewRow.id,
      crew_type: "Base",
      work_date: new Date("2022-02-23"),
      start_time: new Date("2022-02-23T08:00:00.000Z"),
      end_time: new Date("2022-02-23T14:00:00.000Z"),
      job_title: "Operator",
      hourly_rate: "30.00",
    })
    .execute();

  // Total: 14 hours, labour cost: (8 × 25) + (6 × 30) = $380

  return {
    jobsiteId: jobsiteRow.id,
    jobsiteMongoId: "000000000000000000000001",
    crewId: crewRow.id,
    employeeId: employeeRow.id,
    drId: drRow.id,
  };
}

/**
 * Truncates all PostgreSQL tables in dependency-safe order.
 * Fact tables are deleted first (they reference dimension tables via FKs),
 * then dimension tables are deleted.
 *
 * Call this in a beforeEach hook for consumer sync tests (Layer 2) and
 * report query tests (Layer 3) to ensure a clean slate between tests.
 */
export async function truncateAllPgTables(): Promise<void> {
  // Fact tables first — they hold FK references to dimension tables
  const factTables = [
    "fact_employee_work",
    "fact_vehicle_work",
    "fact_material_shipment",
    "fact_non_costed_material",
    "fact_trucking",
    "fact_production",
    "fact_invoice",
  ] as const;

  for (const table of factTables) {
    await db.deleteFrom(table as any).execute();
  }

  // Dimension tables — ordered to respect FK chains within dims
  // (dim_jobsite_material_rate → dim_jobsite_material → dim_jobsite / dim_material)
  // (dim_employee_rate → dim_employee)
  // (dim_vehicle_rate → dim_vehicle)
  // (dim_daily_report → dim_crew + dim_jobsite)
  const dimTables = [
    "dim_jobsite_material_rate",
    "dim_employee_rate",
    "dim_vehicle_rate",
    "dim_daily_report",
    "dim_jobsite_material",
    "dim_employee",
    "dim_vehicle",
    "dim_jobsite",
    "dim_material",
    "dim_company",
    "dim_crew",
  ] as const;

  for (const table of dimTables) {
    await db.deleteFrom(table as any).execute();
  }
}
