apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.1.0
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms1g -Xmx1g
              resources:
                requests:
                  cpu: "100m"
                  memory: "200Mi"
                limits:
                  cpu: "200m"
                  memory: "400Mi"
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
